language: go

go:
 -  master

install:
  - go get -v ./core
  - go get -v ./exec

script:
  - go test -v ./core ./exec -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
